name: Telegram News Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        run: python news_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Guardar estado
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          
          # Asegurar repo limpio (clave!)
          git reset --hard
          
          # Traer cambios remotos
          git pull --rebase
          
          # Añadir archivos generados por el bot
          git add *.txt || true
          git commit -m "update last tweets" || true
          
          # Subir cambios
          git push
